### PR TITLE
Update all objective coefficients in one time

### PR DESCRIPTION
**Pull request by flomnes**
## Short description
This PR is about changing the behavior of `XpressInterface::SetObjectiveCoefficient`, the function which is used to set the objective coefficient for a single variable. This approach proves to be much faster than individual updates.

## Before
`XpressInterface::SetObjectiveCoefficient` immediately changes the coefficients by calling
```c
int const col = variable->index();
CHECK_STATUS(XPRSchgobj(mLp, 1, &col, &coefficient));
```

## After
The model is invalidated by calling `InvalidateModelSynchronization`. When calling `MPSolver::Solve`, all coefficients are extracted in one time
```cpp
void XpressInterface::ExtractObjective() {
  // NOTE: The code assumes that the objective expression does not contain
  //       any non-zero duplicates.

  int const cols = XPRSgetnumcols(mLp);
  // DCHECK_EQ(last_variable_index_, cols);

  unique_ptr<int[]> ind(new int[cols]);
  unique_ptr<double[]> val(new double[cols]);
  for (int j = 0; j < cols; ++j) {
    ind[j] = j;
    val[j] = 0.0;
  }

  const auto& coeffs = solver_->objective_->coefficients_;
  for (auto it = coeffs.begin(); it != coeffs.end(); ++it) {
    int const idx = it->first->index();
    if (variable_is_extracted(idx)) {
      DCHECK_LT(idx, cols);
      val[idx] = it->second;
    }
  }

  CHECK_STATUS(XPRSchgobj(mLp, cols, ind.get(), val.get()));
  CHECK_STATUS(XPRSsetobjoffset(mLp, solver_->Objective().offset()));
}
```

### CODE REVIEW

**Comment by djunglas** [comment]
This can be improved, IMO.
If you replace
```
val[idx] = it->second;
```
by
```
val[idx] += it->second;
```
(note `+=` instead of `=`) then the code is correct even if the objective expression contains duplicates.

`XPRSsetobjoffset()` does not exist. In order to change the constant term in the objective use index -1, see the [reference documentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSchgobj.html).

The code is rather inefficient if the objective is not dense. How about changing the code to something like this to create sparse arrays for calling XPRSchgobj():
```
unique_ptr<int[]> ind(new int[cols + 1];
unique_ptr<double[]> val(new double[cols + 1]);
unique_ptr<int[]> map(new int[cols]);
memset(map.get(), -1, sizeof(*map.get()) * cols); // set all elements in map to -1
int count = 0;

const auto& coeffs = solver_->objective_->coefficients_;
for (auto it = coeffs.begin(); it != coeffs.end(); ++it) {
  int const idx = it->first->index();
  if (variable_is_extracted(idx)) {
    DCHECK_LT(idx, cols);
    if (map[idx] >= 0) { // We already saw this variable
      val[map[idx]] += it->second;
    }
    else { // First time we see this variable
      map[idx] = count;
      ind[count] = idx;
      val[count] = it->second;
      ++count;
    }
  }
}
ind[count] = -1;
val[count] = solver_->Objective().offset();
++count;

CHECK_STATUS(XPRSchgobj(mLp, count, ind.get(), val.get()));
```

**Comment by flomnes** [comment]
> `XPRSsetobjoffset()` does not exist. In order to change the constant term in the objective use index -1, see the [reference documentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSchgobj.html).

This is actually our own function, though I admit the naming is a bit confusing and should be changed

https://github.com/rte-france/or-tools/blob/8564311256a299cbb9b8198d0b72af06d50d4c5f/ortools/linear_solver/xpress_interface.cc#L88-L94

**Comment by pet-mit** [comment]
> This can be improved, IMO. If you replace
> 
> ```
> val[idx] = it->second;
> ```
> 
> by
> 
> ```
> val[idx] += it->second;
> ```
> 
> (note `+=` instead of `=`) then the code is correct even if the objective expression contains duplicates.
> 
> `XPRSsetobjoffset()` does not exist. In order to change the constant term in the objective use index -1, see the [reference documentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSchgobj.html).
> 
> The code is rather inefficient if the objective is not dense. How about changing the code to something like this to create sparse arrays for calling XPRSchgobj():
> 
> ```
> unique_ptr<int[]> ind(new int[cols + 1];
> unique_ptr<double[]> val(new double[cols + 1]);
> unique_ptr<int[]> map(new int[cols]);
> memset(map.get(), -1, sizeof(*map.get()) * cols); // set all elements in map to -1
> int count = 0;
> 
> const auto& coeffs = solver_->objective_->coefficients_;
> for (auto it = coeffs.begin(); it != coeffs.end(); ++it) {
>   int const idx = it->first->index();
>   if (variable_is_extracted(idx)) {
>     DCHECK_LT(idx, cols);
>     if (map[idx] >= 0) { // We already saw this variable
>       val[map[idx]] += it->second;
>     }
>     else { // First time we see this variable
>       map[idx] = count;
>       ind[count] = idx;
>       val[count] = it->second;
>       ++count;
>     }
>   }
> }
> ind[count] = -1;
> val[count] = solver_->Objective().offset();
> ++count;
> 
> CHECK_STATUS(XPRSchgobj(mLp, count, ind.get(), val.get()));
> ```

Thank you Daniel, how about opening a new PR to take into account your proposal. 
I think that @flomnes 's development here, for this specific feature, is not impacted by it.

**Comment by djunglas** [comment]
> > This can be improved, IMO. If you replace
> > ```
> > val[idx] = it->second;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > by
> > ```
> > val[idx] += it->second;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (note `+=` instead of `=`) then the code is correct even if the objective expression contains duplicates.
> > `XPRSsetobjoffset()` does not exist. In order to change the constant term in the objective use index -1, see the [reference documentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSchgobj.html).
> > The code is rather inefficient if the objective is not dense. How about changing the code to something like this to create sparse arrays for calling XPRSchgobj():
> > ```
> > unique_ptr<int[]> ind(new int[cols + 1];
> > unique_ptr<double[]> val(new double[cols + 1]);
> > unique_ptr<int[]> map(new int[cols]);
> > memset(map.get(), -1, sizeof(*map.get()) * cols); // set all elements in map to -1
> > int count = 0;
> > 
> > const auto& coeffs = solver_->objective_->coefficients_;
> > for (auto it = coeffs.begin(); it != coeffs.end(); ++it) {
> >   int const idx = it->first->index();
> >   if (variable_is_extracted(idx)) {
> >     DCHECK_LT(idx, cols);
> >     if (map[idx] >= 0) { // We already saw this variable
> >       val[map[idx]] += it->second;
> >     }
> >     else { // First time we see this variable
> >       map[idx] = count;
> >       ind[count] = idx;
> >       val[count] = it->second;
> >       ++count;
> >     }
> >   }
> > }
> > ind[count] = -1;
> > val[count] = solver_->Objective().offset();
> > ++count;
> > 
> > CHECK_STATUS(XPRSchgobj(mLp, count, ind.get(), val.get()));
> > ```
> 
> Thank you Daniel, how about opening a new PR to take into account your proposal. I think that @flomnes 's development here, for this specific feature, is not impacted by it.

Fine with me. The code is not wrong by itself, so no need to hold back the merge for this.

**Review by pet-mit — APPROVED** [review]

**Pull request merged**
