### PR TITLE
Instead of macros, use fixtures for XPRESS tests

### PR DESCRIPTION
**Pull request by flomnes**
Only difficulty : `UNITTEST_INIT_MIP()` is used in loops, e.g
```cpp
for (const auto& [paramString, control, paramValue] : params) {
  UNITTEST_INIT_MIP();
  std::string xpressParamString = paramString + " " + paramValue;
  solver.SetSolverSpecificParametersAsString(xpressParamString);
  EXPECT_EQ(paramValue, getter.getStringControl(control));
}
```

This has been dealt with by replacing the macro with it's content in each of the 3 loops.

```cpp
for (const auto& [paramString, control, paramValue] : params) {
   MPSolver solver("XPRESS_MIP", MPSolver::XPRESS_MIXED_INTEGER_PROGRAMMING);
   XPRSGetter getter(&solver);
   // ...
}
```

### CODE REVIEW

**Comment by pet-mit** [comment]
Maybe you can use SetUp() instead of constructor in fixture, that way you can call it multiple time (see google doc)

**Comment by flomnes** [comment]
> Maybe you can use SetUp() instead of constructor in fixture, that way you can call it multiple time (see google doc)

According to [this source](https://fuchsia.googlesource.com/third_party/googletest/+/HEAD/googletest/docs/faq.md#ctorvssetup), constructor/destructor should be used whenever possible.

**Comment by pet-mit** [comment]
> > Maybe you can use SetUp() instead of constructor in fixture, that way you can call it multiple time (see google doc)
> 
> According to [this source](http://google.github.io/googletest/faq.html#CtorVsSetUp), constructor/destructor should be used whenever possible.

then maybe, if possible, add a protected reset() method that resets the MIP ?

**Comment by flomnes** [comment]
> > > Maybe you can use SetUp() instead of constructor in fixture, that way you can call it multiple time (see google doc)
> > 
> > 
> > According to [this source](http://google.github.io/googletest/faq.html#CtorVsSetUp), constructor/destructor should be used whenever possible.
> 
> then maybe, if possible, add a protected reset() method that resets the MIP ?

For every test, an `XpressFixtureMIP` is created into the function scope, then destroyed. There is no sharing of a single object among tests.

**Comment by pet-mit** [comment]
> > > > Maybe you can use SetUp() instead of constructor in fixture, that way you can call it multiple time (see google doc)
> > > 
> > > 
> > > According to [this source](http://google.github.io/googletest/faq.html#CtorVsSetUp), constructor/destructor should be used whenever possible.
> > 
> > 
> > then maybe, if possible, add a protected reset() method that resets the MIP ?
> 
> For every test, an `XpressFixtureMIP` is created into the function scope, then destroyed at the end. There is no sharing of a single object among tests.

I meant to solve the loop issue

**Comment by flomnes** [comment]
> > > > > Maybe you can use SetUp() instead of constructor in fixture, that way you can call it multiple time (see google doc)
> > > > 
> > > > 
> > > > According to [this source](http://google.github.io/googletest/faq.html#CtorVsSetUp), constructor/destructor should be used whenever possible.
> > > 
> > > 
> > > then maybe, if possible, add a protected reset() method that resets the MIP ?
> > 
> > 
> > For every test, an `XpressFixtureMIP` is created into the function scope, then destroyed at the end. There is no sharing of a single object among tests.
> 
> I meant, a reset() method would maybe help to solve the loop issue

@pet-mit Since this was only used 3 times (3 for loops), I just copy-pasted the 2 lines of codes each time. I hope the elimination of macros will make it up for this code duplication. Alternatively, I can keep the `UNITTEST_INIT_MIP()` macro, and use it only in these 3 for loops, and isolate it with `#define #undef`.

**Review by sgatto — APPROVED** [review]

**Pull request merged**
